spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
      active: development

  output:
    ansi:
      enabled: always
server:
  address: 0.0.0.0
  port: ${PORT:8080}