spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
      active: development

  output:
    ansi:
      enabled: always
server:
  tomcat:
    accesslog:
      enabled: true